### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by ajnisbet** [odojs/odo#5]

**Comment by tcoats** [comment]
Odo itself runs on Node.js and has a couple of front end auth components that require [odo-ui](https://github.com/odojs/odo-ui).

Odo-ui requires [durandaljs](http://durandaljs.com/), [q](https://github.com/kriskowal/q) and [requirejs](http://requirejs.org/) as a minimum.
They all seem to support:
- IE 6+
- Firefox 2+
- Safari 3.2+
- Chrome 3+
- Opera 10+

Although I haven't checked q and if we're using anything that needs higher requirements.

Odo is legacy and I plan to put effort into [odojs](https://github.com/odojs/odojs) instead.

**Comment by ajnisbet** [comment]
Yeah sorry, I meant to put this on odojs

**Comment by darrenhabib** [comment]
All good, feel free to open another issue on odojs.




I think most parts will work back quite far, but I'll do a stock check and make sure we have some firm support versions. It might require Internet Explorer 10, not sure yet.



Thomas Coats
